Adds omni.isaac.version to experience dependencies (#141)
# Description

This PR fix the `ModuleNotFoundError: No module named
'omni.isaac.version'` for Isaac Sim 4.5

When running `./isaaclab.sh -p
source/standalone/workflows/rsl_rl/train.py --task
Isaac-Cartpole-Direct-v0 --headless --max_iteration 5`

```
Traceback (most recent call last):
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/standalone/workflows/rsl_rl/train.py", line 54, in <module>
    from omni.isaac.lab.envs import (
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/__init__.py", line 45, in <module>
    from . import mdp, ui
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/__init__.py", line 18, in <module>
    from .actions import *  # noqa: F401, F403
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/actions/__init__.py", line 8, in <module>
    from .actions_cfg import *
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/actions/actions_cfg.py", line 9, in <module>
    from omni.isaac.lab.managers.action_manager import ActionTerm, ActionTermCfg
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/__init__.py", line 13, in <module>
    from .action_manager import ActionManager, ActionTerm
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/action_manager.py", line 20, in <module>
    from omni.isaac.lab.assets import AssetBase
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/__init__.py", line 41, in <module>
    from .articulation import Articulation, ArticulationCfg, ArticulationData
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/__init__.py", line 8, in <module>
    from .articulation import Articulation
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/articulation.py", line 22, in <module>
    import omni.isaac.lab.sim as sim_utils
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/__init__.py", line 29, in <module>
    from .converters import *  # noqa: F401, F403
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/__init__.py", line 25, in <module>
    from .urdf_converter import UrdfConverter
  File "/home/toni/Documents/RL/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/urdf_converter.py", line 13, in <module>
    from omni.isaac.version import get_version
ModuleNotFoundError: No module named 'omni.isaac.version'

```
## Type of change

<!-- As you go through the list, delete the ones that are not
applicable. -->

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with
`./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [ ] I have updated the changelog and the corresponding version in the
extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already
exists there

<!--
As you go through the checklist above, you can mark something as done by
putting an x character in it

For example,
- [x] I have done this task
- [ ] I have not done this task
-->